### ISSUE TITLE
Sdata datasets not showing in v27

### ISSUE THREAD

**Issue by stevendoyle2020** [Sage/SData-2.0#162]
Hi, we upgraded from version 26.3 to version 27 of sage 50 accounts.
After the update the company datasets are blank in the Sdata settings.

The firewall rules are set to have the port opened. We have tried changing the sdata service logon to different users and we have tried an uninstall and reinstall all to no avail.

Are you able to help us with this? Is it an issue with v27? 
It worked fine on v26.3.

![v26 3](https://user-images.githubusercontent.com/73286762/96864481-62af3e80-1460-11eb-80ef-5d6f618712b0.JPG)
![v27](https://user-images.githubusercontent.com/73286762/96864490-680c8900-1460-11eb-8286-738e7e2c40ec.JPG)

Regards,
Steven

**Comment by darroncockram** [comment]
We recently came across this issue and are looking to address it. No ETA on when a fix might be available just yet I'm afraid.

**Comment by sagesolution** [comment]
Hi, 

We have the same problem. We tried everything and SData is not listed.  Any update in this issue? Thanks

**Comment by sagesolution** [comment]
Hi @darroncockram is it any update? Sdata driver is affecting some of my applications and unfortunately I can not get back to version 26 without lossing data....

**Comment by darroncockram** [comment]
Afraid not. At this stage all I can say is that we are aware of the issue and are actively investigating a fix. I'll update this thread as soon as I have more info.

**Comment by asterix187** [comment]
We have found the issue and know how to fix but unfortunately the issue is related to an SData DLL that we have no access to. Its probably a 1 line fix so shouldn't be that hard to fix in the next patch release.

**Comment by darroncockram** [comment]
It's the schedule for the next patch release that I am waiting on details for.

Separately to this we are investigating how this issue got missed and looking to implement checks to ensure it does not occur again.

**Comment by asterix187** [comment]
Great news! We have around 80 sites affect so it cant come soon enough!

**Comment by sagesolution** [comment]
@asterix187 well done!  @darroncockram is it possible to get a temporary patch?

**Comment by darroncockram** [comment]
A fix will be included in the v27.1 release but I'm still waiting to hear about any possible hotfix release ahead of that.

**Comment by sagesolution** [comment]
Hi @darroncockram sorry to be nuisance.  is it any ETA?

**Comment by asterix187** [comment]
I would imagine a fix won’t be available until roughly December unless an urgent patch to the problem dll is released specially.

**Comment by darroncockram** [comment]
That's correct. The v27.1 release would be on that rough timescale. I'm still hoping that a hot fix will be released ahead of that but still awaiting on word on if/when this might be. Sorry I don't have any more info on an ETA but will post here as soon as I hear anything.

**Comment by AlfredGreene** [comment]
Do we have any update on V27.1 date or a hotfix?

**Comment by darroncockram** [comment]
Afraid not. I'll post here as soon as I hear anything though.

**Comment by AlfredGreene** [comment]
Just looked at a temp option for importing sales/invoices via import of a csv am i correct Sage50 no longer has an option to import sales/invoices via csv etc until we get the hotfix or v27.1 to resolve the issues.

**Comment by darroncockram** [comment]
You can import SI transactions via the Accounts UI but there is no option to import invoice artefacts other than Sdata or 3rd party applications I'm afraid.

**Comment by darroncockram** [comment]
Looking like the fix for this will not be separately released as a hot fix but will be included in the v27.1 release due for release in December.

**Comment by darroncockram** [comment]
Afraid not. I'm hoping for an early Christmas present though.

**Comment by letoncse** [comment]
I'm facing same issue after update v27. @darroncockram , please let us know when get an update. Thanks !
![image](https://user-images.githubusercontent.com/1812631/100439294-4627a700-309b-11eb-84d9-377dc839db99.png)

**Comment by darroncockram** [comment]
Still no concrete date available for the release yet I'm afraid but will let you know as soon as I hear something further.

**Comment by mfwiniberg** [comment]
One of my clients also has this problem - it's a bit late to discover it once you've upgraded as there's no route back to the old data without considerable loss of time and effort.

SAGE UK Tech support denied this was a problem and actually said that Sage had decided to no longer supply the SDATA service (I have a transcript of a chat session to prove this!) despite what their docs etc say.

A very poor showing from an international company that so many rely on. About time it was fixed, methinks!

**Comment by AlfredGreene** [comment]
We need confirmation from Sage is this is the case and they have pulled plug on Sdata as i will have to advise my clients to consider alternatives to meet their needs. Do we have any update on this fix if it is gong to happen in the update?

**Comment by asterix187** [comment]
It’s been my understand for a few years that sdata is unsupported in Sage 50. It still works (well not it v27 until the v27.1 patch) but its not directly supported.

**Comment by AlfredGreene** [comment]
Our clients were directed by Sage to use for their needs to be honest I would have rather they used the Sage One as it has the api's and would be a lot more easy to integrate with their system that the SData.
Thank god for raspberry Pi to act as a bridge between the web platforms and the Sdata access point on their internal office systems.

**Comment by asterix187** [comment]
We have actually written our own web wrapper over the Sage Data Objects (SDO) framework so that we can perform any action within Sage 50 but have some clients on an older version of our integration. We have upgraded around 40 to our own web service version due to this issue with sdata. It is supposed to be fixed this month though.

**Comment by darroncockram** [comment]
I can confirm that Sage have not pulled the plug on the Sdata service and are not planning to do so. Consumption of the Sdata feeds has always been considered community supported but the service and the Sage 50 Accounts adapter is provided and supported by Sage.

I have no idea why anyone in our support team may have suggested otherwise but they are incorrect and we are continuing to support and ship Sdata for the foreseeable future.

The bug has been fixed and will be included in the v27.1. We are in the late stages of the final regression testing for this release so although I still can't promise a release date at this moment I'm expecting it will be ready within a week.

Appreciate everyone's patience waiting on the fix. Believe me I'm as frustrated as everyone else that we could not release the fix sooner.

**Comment by AlfredGreene** [comment]
That's great when it's deployed and live with clients maybe we should have a zoom party to celebrate :)

**Comment by mfwiniberg** [comment]
A further development: my client, who pays a substantial monthly amount to Sage for Sage50, has spent nearly an hour on the phone with technical support.

Despite claiming that it isn't Sage's problem because SDATA is nothing to do with them (apparently - I thought it was a subsidiary company that produced this etc, but anyway), they did indicate that a fix was going to be released in 27.1, before Christmas (I'm assuming they meant this year!).

I would be happy to purchase a dev kit for Sage if we could do what we wanted with it, but Sage have never been able to reassure me that we actually could (link to our very domain specific custom software for managing customers, invoicing etc - but we also need to be able to manipulate the nominal ledger) and so we haven't bitten. SDATA provides enough functionality to get us most of the way so we've stuck with that plus manual intervention.

Given that they have to compete against the likes of XERO et al, who can import and export just about anything, or even small fry like VT Transaction+ who can do likewise, I'm amazed that they go to such great lengths to prevent people feeding data into their systems.

The only reason my various clients have stuck with Sage is because (as with Microsoft office) its the one that everyone (including their accountants) use, even though it isn't particularly suited to the way they run their business.

It's about time Sage had some real competition, because they sure as hell seem to be losing the plot and I've a number of firms that would switch tomorrow if they could escape the lock-in.

**Comment by darroncockram** [comment]
> It’s been my understand for a few years that sdata is unsupported in Sage 50. It still works (well not it v27 until the v27.1 patch) but its not directly supported.

For clarity Sdata and the Sage 50 Adapter is officially supported by Sage (as evidenced by us releasing a patch for it). What we don't provide direct support for is for 3rd party developers consuming - training, certification, code samples, help/advice, etc. The official line is that Sdata is considered to be a self documenting system and consumption is 'community supported' i.e. via these forums.

There were originally grander plans for Sdata and support within the 3rd party development community but unfortunately this has never come to pass.

**Comment by darroncockram** [comment]
> Despite claiming that it isn't Sage's problem because SDATA is nothing to do with them (apparently - I thought it was a subsidiary company that produced this etc, but anyway), they did indicate that a fix was going to be released in 27.1, before Christmas (I'm assuming they meant this year!).

Again just for clarity - Sdata isn't a company at all and never has been. It's a general purpose standard that Sage developed many years ago and made free/open to the community.

An implementation of Sdata was subsequently included in a number of Sage products, including Sage 50 Accounts that 99% of the questions we see on these forums relate to. You can think of Sdata as being like HTML - and the Sage 50 Accounts adapter as being like Chrome in that analogy (or perhaps Internet Explorer if you're feeling unkind!). Technically anyone can implement Sdata and/or an Sdata adapter in the same way that anyone could create a web browser - they just need to adhere to the standard.

**Comment by mfwiniberg** [comment]
Hi Darron,

Thanks for clearing that up - we've been users of SDATA since it was first included in SAGE 50 and to have it suddenly stop working at our clients was upsetting as you might imagine. To then be told by tech support that it must be a third party problem (despite the Sage internal web server no longer publishing the GCRM URL all of a sudden) and that SDATA support had been dropped was something of a bombshell.

I realise that the SDATA spec etc is a community supported project, but it is meaningless if Sage are not prepared to provide the web service it relies on so the two are inextricably linked.

To be honest, I've never understood why the Sage ODBC drivers are read-only - it would make life so much easier for us software developers to interface to your systems if it provided full connectivity, but there we go 8)

**Comment by darroncockram** [comment]
> Thanks for clearing that up - we've been users of SDATA since it was first included in SAGE 50 and to have it suddenly stop working at our clients was upsetting as you might imagine. To then be told by tech support that it must be a third party problem (despite the Sage internal web server no longer publishing the GCRM URL all of a sudden) and that SDATA support had been dropped was something of a bombshell.

This is personal opinion rather than anything official but I suspect that this will have been a bit of a Chinese whispers type problem within the support function. We don't provide direct 3rd party support for consuming the Sdata feeds in Sage 50 Accounts and I suspect that has somehow been morphed in to the incorrect message that we do not provide any support at all for Sdata.

It's small consolation but this has been the first significant issue we've had with the Sdata implementation in Sage 50 Accounts since it was released. There have been other issues of course, no piece of software is ever perfect, but nothing anything like as fundamental as this one. On the positive side process have been put in place as part of the release testing to detect and and stop this sort of thing happening again.

> I realise that the SDATA spec etc is a community supported project, but it is meaningless if Sage are not prepared to provide the web service it relies on so the two are inextricably linked.

Officially they are not considered linked at all. As the Sdata spec is an open standard this means anyone could come along and implement a service and adapters to work with any Sage product (or even non-Sage products). In theory Sage could decide to remove the Sdata implementation from Sage 50 Accounts (and just to stress here that I'm talking hypothetically - there are no plans to do this) and this would not stop any other implementation working. Following the web browser example above it would be like Google deciding to stop shipping Chrome - it would not stop people using the Internet, they would just switch to a different implementation (browser).

Of course where this analogy falls over a little is that Sage are the only ones to have implemented any Sdata services or adapters

> To be honest, I've never understood why the Sage ODBC drivers are read-only - it would make life so much easier for us software developers to interface to your systems if it provided full connectivity, but there we go 8)

I may be getting well away from the topic of this thread/forum but hopefully I can provide some interesting insights on this. There are a fair few reasons why the ODBC driver does not support writes but the two main ones are:

1. The ODBC driver is not actually supported for 3rd party consumption at all. Technically not even for reading . It actually only exists to support running reports via Report Designer and in theory Sage could pull it at any time without warning and replace it with something else that still fulfilled the ability to run reports via Report Designer. Again going to stress the theoretical nature of that as there are no plans that I'm aware of to do this, just that it could and that is one of the reason it is not supported for direct consumption. The ODBC driver isn't fully compliant with the ODBC standard, it just provides enough functionality to be able to run the reports and anything else is actually just an accidental bonus. The official line is that if you want to report on or extract data from Sage 50 Accounts then you should use Report Designer or SDO (the Accounts-specific SDK).

2. It is near impossible to properly implement and enforce business rules in the ODBC driver. As I'm sure you are aware there are a lot of business rules in Sage 50 Accounts, many of which go way beyond simple data integrity rules such as field length, range, and foreign key relationships, etc. Even inserting a single transaction is not a simple operation as it affects multiple data rows (this is double entry book keeping after all) and multiple tables. SQL INSERT statements simply can't properly articulate these rules. To stand any chance of this you'd need 100's of bespoke functions/extensions and if you are going to those lengths you may as well use the SDK.

As I say that last bit is a tad off topic but hopefully give some idea of why ODBC writes aren't available.

**Comment by mfwiniberg** [comment]
Thanks for the further detail - having implemented a number of back-office credit card transaction systems I can appreciate the difficulties in allowing unfettered access to software that has to comply with strict rules and legal requirements. Nevertheless, given that we need to link MS SQL Server, Python, a web app and MS Access (!) running on a mixture of operating systems into SAGE accounts we actually use an ODBC interface to talk to SDATA, I can't see any reason why a SAGE ODBC driver couldn't - in theory at least - provide equivalent functionality. Of course, whether Sage would want to do that is an entirely different matter 8)

As I said we have used SDATA since it was introduced, and have never had any trouble with it (although the documentation was somewhat impenetrable for v 1.0) so to have an upgrade break it (which wasn't noticed for a couple of days because of the reduced level of relevant business resulting from the pandemic) was a bit of a shock, not least because you can't roll-back easily without having to re-enter data.

My only other thought is that - to the end customer - all this stuff is Sage. The fact that 'internally' it isn't seen that way cuts no ice with consumers (as I've learnt the hard way) and the 'it must be somebody else's fault' tone adopted by the usually helpful Sage tech support team only added fuel to the fire.

Your candor and assistance is greatly appreciated - thank you.

**Comment by darroncockram** [comment]
> My only other thought is that - to the end customer - all this stuff is Sage. The fact that 'internally' it isn't seen that way cuts no ice with consumers (as I've learnt the hard way) and the 'it must be somebody else's fault' tone adopted by the usually helpful Sage tech support team only added fuel to the fire.

Completely agree. I'll see if I can find out who to raise this with in our support team so we can get a consistent (and correct!) response to queries about Sdata that they receive.

**Comment by asterix187** [comment]
v27.1 has just been released. We are currently testing it so I will update the thread shortly.

**Comment by asterix187** [comment]
We have done a test and it appears that in some circumstances the datasets are duplicated multiple times on the endpoint. This was on an upgrade from v27.

![image](https://user-images.githubusercontent.com/7346013/102994802-b2b98880-4517-11eb-9fce-d63f355b5728.png)

That said I have just done a completely clean install and added in the demo data and it all appears okay within the UI.

![image](https://user-images.githubusercontent.com/7346013/102994755-9584ba00-4517-11eb-8787-5e81cafa1d7f.png)

**Comment by darroncockram** [comment]
Closing as original issue resolved in v27.1 release

**Comment by mfwiniberg** [comment]
It is worth emphasising that upgrading to 27.1 does not fix this - you have to completely remove Sage and then install with the 27.1 installer.

**Comment by mfwiniberg** [comment]
Also, it isn't completely fixed. We run Sage with the data held on a network share. I have updated the data service on the server to 27.1 (by a clean install, not an upgrade) and also done a clean install on the client PC - still no SDATA GCRM URL published.

Can you confirm that it has been tested and found working in such a configuration please?

**Comment by asterix187** [comment]
Did you make sure the sdata service is running under a network user account that has access to the network share? Have you tried connecting to a copy of the data locally?

It works okay for us in testing.

________________________________

**Comment by mfwiniberg** [comment]
Hi, Thanks for getting back to me.

I will double check that, although the previous setup was made the same way and was working as expected. The installation is done as the domain administrator, but I'll check that the service account does have access to the share...

It does, but just in case I changed the service to use the domain admin account - still nothing...

Mike

**Comment by mfwiniberg** [comment]
Well, in the end I have solved the businesses problem, but I'm still not convinced this has really been fixed:

I was installing the copy of Sage that I wanted to provide SDATA service on a Windows 10 PC that is dedicated to the interface to SDATA and hosts the software that talks to the URL.

No amount of uninstalling and clean re-installing of Sage on here would cause a GCRM URL to be published.

So, off I go to the server that holds the Sage Data network share. An upgrade install of the Data Connector to 27.1 did not work. 

I then did an uninstall and clean reinstall of the data connector, and still nothing.

So in desperation, I uninstalled the data connector and did a clean install of the full sage 50 27.1 on the server. After registering this and opening the accounts data share via its UNC, lo and behold an SDATA URL is available.

I went back the the dedicated Sage interface PC and used the server's provided URL (after opening the firewall) and away everything went.

It is important to note that we have never had a problem with the SDATA service/URL before and we have been using it since it first came out. Each upgrade has worked seamlessly and without requiring any special configuration of system accounts for access etc.

At least we are now able to carry on our business again after a couple of months of having to do everything manually.

Only fair to point out that the firm came "that close" to moving to another accounting provider as a result of this, despite the disruption that would cause. I made the point above that, whatever the internal view of the SDATA facility, to Sage customers it is all Sage, and - if Sage are going to compete with the likes of Xero et al - they need to remember that customers don't care how they view their own ecosystem internally.

BT take note also! 8)
